[package]
name = "crackers_bin"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

members = ["crackers"]

[dependencies]
elf = "0.7.4"
jingle = { path = "../../RustroverProjects/jingle/jingle" }
crackers = { path = "../crackers/crackers" }
z3 = { git = "https://github.com/prove-rs/z3.rs.git", rev = "247d308" }
thiserror = "1.0.58"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
