[sleigh]
ghidra_path = "/Applications/ghidra"

[synthesis]
strategy = "optimize"
max_candidates_per_slot = 200

[specification]
path = "bin/execve_instrs.bin"
max_instructions = 5

[library]
path = "bin/libc_wrapper"
max_gadget_length = 8
random_sample_size = 10000
random_sample_seed = 0x294


[constraint.precondition.register]
RAX = 0
RCX = 0x440f30
RDX = 0x7fffffffe608
RBX = 0x400538
RSP = 0x7fffffffe3b8
RBP = 0x403af0
RSI = 0x7fffffffe5f8
RDI = 1
R8 = 0
R9 = 6
R10 = 0x36f8
R11 = 0x206
R12 = 0x403b90
R13 = 0x0
R14 = 0x4ae018
R15 = 0x400538
GS = 0
FS = 0

[constraint.pointer]
min = 0x7ffffffde000
max = 0x7ffffffff000