[sleigh]
ghidra_path = "/Applications/ghidra"

[synthesis]
strategy = "sat"
max_candidates_per_slot = 200
parallel = 4
log_level = "INFO"

[specification]
path = "bin/mmap_call2.bin"
max_instructions = 7

[library]
path = "bin/libc_wrapper"
max_gadget_length = 6
random_sample_size = 10000

[constraint.precondition.register]
RAX = 0
RCX = 0x440f30
RDX = 0x7fffffffe608
RBX = 0x400538
RSP = 0x7fffffffe638
RBP = 0x403af0
RSI = 0x7fffffffe5f8
RDI = 1
R8 = 0
R9 = 6
R10 = 0x36f8
R11 = 0x206
R12 = 0x403b90
R13 = 0x0
R14 = 0x4ae018
R15 = 0x400538
GS = 0
FS = 0

[constraint.postcondition.register]
RSI = 1024
RDX = 0x7b
RCX = 0x20

[constraint.pointer.read]
min = 0x7ffffffde000
max = 0x7ffffffff000

[constraint.pointer.write]
min = 0x7ffffffde000
max = 0x7ffffffff000
