[sleigh]
ghidra_path = "/Applications/ghidra"

[synthesis]
strategy = "sat"
max_candidates_per_slot = 200
parallel = 8

[specification]
path = "bin/execve.bin"
max_instructions = 3

[library]
path = "bin/libc_wrapper"
max_gadget_length = 8
random_sample_size = 10000


[constraint.precondition.register]
RAX = 0
RCX = 0x440f30
RDX = 0x7fffffffe608
RBX = 0x400538
RSP = 0x7fffffffe3b8
RBP = 0x403af0
RSI = 0x7fffffffe5f8
RDI = 1
R8 = 0
R9 = 6
R10 = 0x36f8
R11 = 0x206
R12 = 0x403b90
R13 = 0x0
R14 = 0x4ae018
R15 = 0x400538

[constraint.pointer.read]
min = 0x7fffffffde00
max = 0x7ffffffff000

[constraint.pointer.write]
min = 0x400000
max = 0x4a8000