[workspace]
pr_branch_prefix = "release-plz-" # PR branch prefix
pr_labels = ["release"] # add the `release` label to the release Pull Request

[[package]] # the double square brackets define a TOML table array
name = "crackers_python"
publish = false # disable `cargo publish` for `package_a`
version_group = "crackers"

[[package]]
name = "crackers"
version_group = "crackers"