[sleigh]
ghidra_path = "/Applications/ghidra"

[synthesis]
strategy = "optimize"

[specification]
path = "bin/minimized.bin"
max_instructions = 11

[library]
path = "bin/vuln"
max_gadget_length = 8
random_sample_size = 500
random_sample_seed = 0x2983246

[constraint.precondition.register]
EAX = 0
EBX = 0
EDX = 0
XMM0 = 0
ESP = 0x0009_d200

[constraint.pointer]
min = 0x0009_0000
max = 0x000a_0000