[sleigh]
ghidra_path = "/Applications/ghidra"

[synthesis]
strategy = "optimize"
max_candidates_per_slot = 100

[specification]
path = "bin/minimized.bin"
max_instructions = 11

[library]
path = "bin/vuln"
max_gadget_length = 4
random_sample_size = 10000
random_sample_seed = 0x2924

[constraint.precondition.register]
EAX = 0
EBX = 0
EDX = 0
XMM0 = 0
ESP = 0x0009_8000

[constraint.pointer]
min = 0x0008_0000
max = 0x000a_0000