name: Python Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: ${{ matrix.session }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        session: [ruff, mypy]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Create uv virtual environment
        run: |
          uv venv --project crackers_python
      - name: Install dev dependencies
        run: |
          uv sync --locked --project crackers_python --dev --active
      - name: Run nox session
        run: |
          uv run --project crackers_python nox -s ${{ matrix.session }}
